config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_param, only: [:edit,:show,:update,:destroy]
  
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def edit
    
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article Was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def update
    
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def show
    
  end
  
  def destroy
    if  @article.destroy
      flash[:notice] = "Article was successfully Destroyed"
      redirect_to articles_path
    else
      render 'destroy'
    end
  end
  
  private
    def set_param
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title,:description)
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
  
  def about
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2> The Following prevented the articles from being created</h2>
<ul>
  <% @article.errors.full_messages.each do  |msg| %>
  <li><%= msg%></li>
  <% end%>
</ul>
<% end %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description%><br/>
    <%= f.text_area :description%>
  </p>
  <p>
    <%= f.submit%>
  </p>
<% end %>

<%= link_to 'Back to Show all Articles', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit Existing Article</h1>

<%= render 'form'%>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>
<p>
<%= link_to "Create new Article", new_article_path %>
</p>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  
  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title%></td>
    <td><%= article.description%></td>
    <td><%= link_to 'Edit Article', edit_article_path(article) %></td>
    <td><%= link_to 'Show Article', article_path(article)%> </td>
    <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you Sure?'} %></td>
  </tr>
  <% end %>
  
  <p><%= link_to 'Home','/'%></p>
</table>

app/views/articles/new.html.erb
<h1> Create an Article<h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected Article</h1>

<p>
  Title: <%= @article.title%>
</p>

<p>
  Description: <%= @article.description%>
</p>
<%= link_to 'Edit this Article', edit_article_path(@article)%> |
<%= link_to 'Back to Show All Articles', articles_path %>

app/views/layouts/_messages.html.erb
  <% flash.each do |name,msg| %>
    <ul>
      <li><%= msg%></li>
    </ul>
  <% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/messages'%>
  <%= yield %>


</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
</head>
<style>
  #header {
    background-color: #980000;
    color: white;
    text-align: center;
    padding: 5px;
  }
  
  ul{
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    border: 1px solid #e7e7e7;
    background-color: #f3f3f3;
  }
  
  li{
    float: left;
  }
  
   li a{
    display: block;
    color: #666;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
  }
  
  li a:hover:not(.active){
    background-color:#993333;
    color: white;
  }
  
  li a.active{
    color:white;
    background-color: #993333;
  }  
  
  #para{
    color: gray;
    position: relative;
  }
  
  
  #footer {
    background-color:red;
    color:white;
    clear:both;
    text-align:center;
    position: fixed;
    bottom: 0;
    left: 0;
}
</style>
<body>

<ul>
  <li class = "active"><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'About', about_path %></li>
</ul>

<div id = "header">
  <h1>
    Blog
  </h1>
</div>

<div id = para><p>
  About Page
</p>
</div>


<div id="footer">
Copyright © KJones
</div>

</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
</head>
<style>
  #header {
    background-color: #980000;
    color: white;
    text-align: center;
    padding: 5px;
  }
  
  ul{
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    border: 1px solid #e7e7e7;
    background-color: #f3f3f3;
  }
  
  li{
    float: left;
  }
  
  li a{
    display: block;
    color: #666;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
  }
  
  li a:hover:not(.active){
    background-color:#993333;
    color: white;
  }
  
  li a.active{
    color:white;
    background-color: #993333;
  }  
  
  #para{
    color: gray;
    position: relative;
  }
  
  
  #footer {
    background-color:red;
    color:white;
    clear:both;
    text-align:center;
    position: fixed;
    bottom: 0;
    left: 0;
}
</style>
<body>

<ul>
  <li class = "active"><%= link_to 'Home', root_path %></li>
  <li><%=link_to 'Articles',articles_path%></li>
  <li><%= link_to 'About', about_path %></li>
</ul>

<div id = "header">
  <h1>
    Blog
  </h1>
</div>

<div id = para><p>
  Welcome to the blog hope you have a good time
</p>
</div>


<div id="footer">
Copyright © KJones
</div>

</body>
</html>